version: '3'
services:
  postgres-dev:
    image: 'postgres:latest'
    restart: always
    env_file: 
      - .env.dev
    ports:
      - '6000:5432'
  postgres-int:
    image: 'postgres:latest'
    restart: always
    env_file: 
      - .env.int
    ports:
      - '6001:5432'
  postgres-acc:
    image: 'postgres:latest'
    restart: always
    env_file: 
      - .env.acc
    ports:
      - '6002:5432'
  postgres-prod:
    image: 'postgres:latest'
    restart: always
    env_file: 
      - .env.prod
    ports:
      - '6003:5432'
  jenkins:
    image: 'jenkins/jenkins:lts'
    privileged: true
    user: root
    ports:
      - '8081:8080'
      - '50001:50000'
    environment:
      - JENKINS_HOME=/root/jenkins-data
    volumes:
      - /home/${myname}/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker

